### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by sunreview** [fccaikai/Gan_Kotlin#2]
你是怎么去掉底部导航栏的滑动效果的 谢谢

**Comment by caikaidev** [comment]
左右切换的滑动效果？底部Tab是用BottomNavigationView+Fragment实现的，本就不支持左右滑动切换tab

**Comment by sunreview** [comment]
问下 ganIO 往期的api是什么呢

**Comment by caikaidev** [comment]
emmm.接口定义都在Api.kt里面啊，仔细看一下源码，就能找到

**Comment by sunreview** [comment]
好想知道你 往期 这个fragment是怎么做出来的 ，你能大概描述下吗

**Comment by caikaidev** [comment]
大兄弟你是做android开发的嘛，我有空看一下吧，这个很久之前的项目了

**Comment by caikaidev** [comment]
@tomridder 就用了一个RecyclerView

**Comment by sunreview** [comment]
我知道是RecyclerView ，而且是用retrofit+rxjava把数据解析到本地，然后加载到recyclerView上。
问题是我不知道你的 API接口怎么写的，和用retrofit解析数据到本地的过程（其余的hot  fragment和girl fragment我都实现了，只差这个往期fragment了）

**Comment by sunreview** [comment]
就是通过哪个gankAPI能得到你那个recyclerView呢

**Comment by caikaidev** [comment]
emmm...[HistoryFragment](https://github.com/fccaikai/Gan_Kotlin/blob/master/app/src/main/java/com/kcode/gankotlin/ui/fragment/HistoryFragment.kt) 中有一个`loadPublishedDate `方法

**Comment by sunreview** [comment]
到底接口是怎么写的啊 我不懂kotlin 你给我说一下大致算法
